### ISSUE TITLE
大神，要不要把部署文档详细一点，直接go run main.go router.go 跑不起来，缺各种依赖

### ISSUE THREAD

**Issue by richard2018** [dangyanglim/go_cnode#1]

**Comment by dangyanglim** [comment]
你发下报错给我看看，go -V看看版本要1.11后面

**Comment by dangyanglim** [comment]
有一个包需要翻墙，我改成不需要了，另外git的版本不能太低git2.0以上

**Comment by dangyanglim** [comment]
我在一个空白的centos系统上直接也跑通了，git要2.19

**Comment by richard2018** [comment]
windowns环境, git,go版本都没问题。
 C:\sources\me\go_cnode> go run main.go router.go
go: finding github.com/gorilla/sessions v1.1.3
go: finding github.com/golang/net v0.0.0-20190424024845-afe8014c977f
go: finding github.com/ugorji/go/codec v0.0.0-20181209151446-772ced7fd4c2
go: finding github.com/stretchr/testify v1.2.2
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: finding github.com/gorilla/securecookie v1.1.1
go: finding github.com/gorilla/context v1.1.1
go: google.golang.org/appengine@v1.5.0: unrecognized import path "google.golang.org/appengine" (https fetch: Get https://google.golang.org/appengine?go-get=1: dial tcp 216.239.37.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)
go: error loading module requirements

**Comment by richard2018** [comment]
可以连gxxgle

**Comment by dangyanglim** [comment]
https://google.golang.org/appengine?go-get=1，这个依赖包需要翻墙，你git pull一下，我把它改成不翻墙了

**Comment by dangyanglim** [comment]
git pull 再重新go run main.go router.go

**Comment by richard2018** [comment]
非常棒，可以了，3Q.
